name: heroku-deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_KEY_LVL4_PROJECT }}
      run: heroku login 
      

    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_KEY_LVL4_PROJECT }}
      run: |
        heroku git:remote -a ${{ secrets.HEROKU_APP_NAME_LVL4_PROJECT }}
        git push heroku master
